@startuml
class Command {
    +id: integer
'    Описание команды (поле комментария в свободной форме)
    +decription: text
'    Условия привлечения команды (поле комментария
'    в свободной форме), в поле комментария как шаблон
'    задать пункты: Возможный объем привлечения,
'    Длительность привлечения, Информация о ставках,
'    Возможность привлечения как аутстафф без руководителя)
    +conditions: text
'    Список и ссылки на карточки членов команды
    +command_stuff: integer
}
@enduml