@startuml
class CompanyCommand {
    +id: integer
'    Описание команды (поле комментария в свободной форме)
    +decription: text
'    Условия привлечения команды (поле комментария
'    в свободной форме), в поле комментария как шаблон
'    задать пункты: Возможный объем привлечения,
'    Длительность привлечения, Информация о ставках,
'    Возможность привлечения как аутстафф без руководителя)
    +conditions: text
'    Файлы (Файл категории Сертификат, обязательно должен
'    иметь тестовое описание, и попадать в поисковую выдачу
'    при поиске по сертификатам)
    +files: integer[]
'    Ресурсы (группы файлов 1) общая информация по ресурсам
'    и ставкам 2) резюме (с возможностью проставить
'    комментарий, текст должен быть длинный)
    +resources_files: integer[]
    +person_cards: integer[]
}
@enduml

{При наличии информации возможность заполнить таблицу:

Специализация (аналитик/разработчик и тп)

Грейд

Ставка (в час/без учёта НДС)

Уровень владения англ.языком

Резюме на русском языке
(возможна подгрузка нескольких файлов)

Резюме на английском языке
(возможна подгрузка нескольких файлов)

При наличии карточки ресурса в системе возможность
связать её с данным юрлицом, при этом в таблице
добавляется поле – Ссылка с возможностью перехода
на карточку ресурса.} - данная информация
связана с классом Employee членов команды и может быть
вытянута оттуда