@startuml
class ProjectExperience {
    +id: integer
'    номер сделки
    +contract_number: varchar
'    название
    +name: varchar
'    проектная роль
    +project_role: varchar
'    проектные работы
    +project_works: text
}
@enduml